# Generated by Django 3.2.16 on 2023-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231029_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsinrecipe',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/photo', verbose_name='Картинка'),
        ),
    ]
